export default [
  {
    id: "1",
    title: "Task 1",
    description: "Description 1",
    assignee: "John Doe",
    expirationDate: new Date(),
    status: "pending",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Task 2",
    description: "Description 2",
    assignee: "Jane Doe",
    expirationDate: new Date(),
    status: "in_progress",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Task 3",
    description: "Description 3",
    assignee: "John Doe",
    expirationDate: new Date(),
    status: "completed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
